### ISSUE TITLE
关于图片路径的有什么好的建议吗

### ISSUE THREAD

**Issue by ghost** [coderzh/gohugo.org#15]
1.默认情况下 hugo 需要将图片放到 static 目录下才能够访问，但是 Typora 图片预览是根据 md 文档的相对路径。假设下面这种情况：
```
文件目录：hugo/content/posts/title.md，
使用 Typora 粘贴图片到 static 目录时，md文档里图片的链接是： ../../static/pic.png，
这时候如果使用 hugo server 渲染，访问文档时发起的 url 请求是：http://127.0.0.1:1313/posts/title/，
然而此时因为图片的相对路径，请求图片的 url 是：http://127.0.0.1:1313/static/pic.png
```
这种情况就会导致图片找不到，因为实际上图片的 url 是：http://127.0.0.1:1313/pic.png

**Comment by ghost** [comment]
已解决，使用 uglyURLs 参数

**Comment by kingfsen** [comment]
直接在github上开一个repository，专门用于存放图片，然后网站引用地址就可以了。

**Comment by roaming-debug** [comment]
> 直接在github上开一个repository，专门用于存放图片，然后网站引用地址就可以了。

这也太累了吧==

**Comment by roaming-debug** [comment]
> 已解决，使用 uglyURLs 参数

请问标签和分类不显示你是怎么解决的呢，是自己手动修改主题吗==
